apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: eshop-webapp-health-check
  namespace: prod
spec:
  metrics:
  - name: webapp-http-check
    interval: 5s
    count: 10
    failureLimit: 1
    successCondition: result == "200"
    provider:
      web:
        url: "http://eshop-webapp.prod.svc.cluster.local/"
        timeoutSeconds: 5