apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: eshop-webapp
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eshop-webapp
  strategy:
    canary:
      analysis:
        templates:
          - templateName: eshop-webapp-health-check
      steps:
        - setWeight: 10
        - pause: { duration: 1m }
        - analysis:
            templates:
              - templateName: eshop-webapp-health-check
        - setWeight: 50
        - pause: { duration: 1m }
        - analysis:
            templates:
              - templateName: eshop-webapp-health-check
        - setWeight: 100
  template:
    metadata:
      labels:
        app: eshop-webapp
    spec:
      containers:
      - name: eshop-webapp
        image: pro690finalacr.azurecr.io/eshoponweb/web:5
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"
        - name: ASPNETCORE_HTTP_PORTS
          value: "80"
        - name: UseOnlyInMemoryDatabase
          value: "true"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3