apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-webapp
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-webapp
  template:
    metadata:
      labels:
        app: eshop-webapp
    spec:
      containers:
      - name: eshop-webapp
        image: pro690finalacr.azurecr.io/eshoponweb/web:6
        ports:
        - containerPort: 80
