apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-webapp
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-webapp
  template:
    metadata:
      labels:
        app: eshop-webapp
    spec:
      containers:
      - name: eshop-webapp
        image: your-registry/eshop-webapp:latest
        ports:
        - containerPort: 80
