apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAgInBybzY5MGZpbmFsYWNyLmF6dXJlY3IuaW8iOiB7DQogICAgICAgICAgInVzZXJuYW1lIjogImZhMDBlMGNhLWQ0NDYtNGI3Ni1iNWMyLTU2OTI2MjAyZWI0MCIsDQogICAgICAgICAgInBhc3N3b3JkIjogIk5sSThRflpnVFNZZ0tINHVqdXV1R3F+cjB0NlllT1lIUzZwLmdha1ciLA0KICAgICAgICAgICJlbWFpbCI6ICJ2cGxhdG9ub3ZtYWlsQGdtYWlsLmNvbSINCiAgICAgICAgfQ0KICAgICAgfQ0KICB9